const router = require("express").Router();
const district = require("./district");
const division = require("./division");
const halqa = require("./halqa");
const maqam = require("./maqam");
const province = require("./province");
const tehsil = require("./tehsil");
const filterHalqas = require("./filterHalqa");
const ilaqa = require("./ilaqa");
const country = require("./markaz");

router.use("/country", country);
router.use("/province", province);
router.use("/division", division);
router.use("/maqam", maqam);
router.use("/district", district);
router.use("/tehsil", tehsil);
router.use("/ilaqa", ilaqa);
router.use("/halqa", halqa);
router.use("/filter", filterHalqas);
module.exports = router;
