const divisionData = [
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Rawalpindi",
    tehsil: "Kalar Saidan",
    unit: "Kalar Saidan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Rawalpindi",
    tehsil: "Rawalpindi",
    unit: "Kahuta",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Rawalpindi",
    tehsil: "Gujar khan",
    unit: "Gujar khan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Rawalpindi",
    tehsil: "Gujar khan",
    unit: "Doltala",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Attock",
    tehsil: "Pindi Ghep",
    unit: "Khaur",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Attock",
    tehsil: "Fatehjang",
    unit: "Fatehjang",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Attock",
    tehsil: "Khaur",
    unit: "Pindsultani",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Attock",
    tehsil: "Fatehjang",
    unit: "Mohala Usman Ghani",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Attock",
    tehsil: "Pindi Ghep",
    unit: "Ahmedal",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Jhelum",
    tehsil: "Sohawa",
    unit: "Sohawa",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Chakwal",
    tehsil: "Chakwal",
    unit: "Allama Iqbal Town",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Chakwal",
    tehsil: "Chakwal",
    unit: "Madina Town",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Chakwal",
    tehsil: "Chakwal",
    unit: "Shumali Muhala",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Chakwal",
    tehsil: "Chakwal",
    unit: "Gojra",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Chakwal",
    tehsil: "Chakwal",
    unit: "Bhoon",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Chakwal",
    tehsil: "Chakwal",
    unit: "Rata Shareef",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Talagang",
    tehsil: "Talagang",
    unit: "Mohala Garb",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Talagang",
    tehsil: "Talagang",
    unit: "Saghar",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Rawalpindi",
    district: "Talagang",
    tehsil: "Talagang",
    unit: "latee",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Kharian",
    unit: "Gulyana Road",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Kharian",
    unit: "Khariat Cannat",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Kharian",
    unit: "Burch",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Kharian",
    unit: "Mandheer",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Kharian",
    unit: "Dhani",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Kharian",
    unit: "Govt College Kharian",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Gujrat",
    unit: "Tanada",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Lalamusa",
    unit: "Khawas pur",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Lalamusa",
    unit: "Main Bazar",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Lalamusa",
    unit: "Kunja",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Lalamusa",
    unit: "Sardar pura",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Kharian",
    unit: "Dhoak Kasab",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Gujrat",
    tehsil: "Kharian",
    unit: "Sikriali",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Phalia",
    unit: "Ghazali hostal",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Phalia",
    unit: "Heilan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Phalia",
    unit: "Parian Wali",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Phalia",
    unit: "Aziz Abad",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Phalia",
    unit: "Eid Gha Mohallah",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Mandi Bahawuddin",
    unit: "Ihsan Abad",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Mandi Bahawuddin",
    unit: "Faiz Abad",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Mandi Bahawuddin",
    unit: "Al Janat Town",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Mandi Bahawuddin",
    unit: "Harya",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Mandi Bahawuddin",
    unit: "Saana",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujrat",
    district: "Mandi Bahawuddin",
    tehsil: "Mandi Bahawuddin",
    unit: "Lakhny wala",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Sargodha",
    unit: "39 Chak",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Sargodha",
    unit: "42 Chak",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Kotmomin",
    unit: "Kotmomin",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Kotmomin",
    unit: "Liliani",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Bhalwal",
    unit: "Phularwan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Bhalwal",
    unit: "Al Fazal Town",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Bhalwal",
    unit: "Mukhtar Colony",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Bhalwal",
    unit: "Islam Pura",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Bhalwal",
    unit: "7 Chak",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Bhalwal",
    unit: "Govt. Graduate College",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Bhalwal",
    unit: "Govt. Commerce College",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Bhera",
    unit: "Bhera",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Bhera",
    unit: "Miani",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Shahpur",
    unit: "Shahpur",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Shahpur",
    unit: "Jhawarian",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Shahpur",
    unit: "Kot Kamboh",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Sargodha",
    tehsil: "Shahpur",
    unit: "Goverment College Shahpur",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Khushab",
    tehsil: "Khushab",
    unit: "Khushab City",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Khushab",
    tehsil: "Khushab",
    unit: "Johrabad City",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Khushab",
    tehsil: "Khushab",
    unit: "12 Block",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Khushab",
    tehsil: "Khushab",
    unit: "Iftikhar town",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Khushab",
    tehsil: "Khushab",
    unit: "Dar-Us-Salam",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Khushab",
    tehsil: "Khushab",
    unit: "Govt College Johrabad",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Khushab",
    tehsil: "Khushab",
    unit: "Education University Johrabad",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sargodha",
    district: "Khushab",
    tehsil: "Peelowains",
    unit: "Peelowains",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Mianwali",
    tehsil: "Mianwali",
    unit: "Mianwali University",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Mianwali",
    tehsil: "Mianwali",
    unit: "Govt College Mianwali",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Mianwali",
    tehsil: "Mianwali",
    unit: "Punjab College Mianwali",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Mianwali",
    tehsil: "Piplan",
    unit: "Degree College Piplan",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Mianwali",
    tehsil: "Mianwali",
    unit: "Umar Farooq u",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Mianwali",
    tehsil: "Mianwali",
    unit: "Dawood Khel",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Mianwali",
    tehsil: "Piplan",
    unit: "Piplan",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Mianwali",
    tehsil: "Piplan",
    unit: "Kundian",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Mianwali",
    tehsil: "Piplan",
    unit: "Chashma u",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Bhakkar",
    tehsil: "KaloorKot",
    unit: "Govt College Kalur Kot",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Bhakkar",
    tehsil: "Bhakkar",
    unit: "Degree College Bayhal",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Bhakkar",
    tehsil: "Bhakkar",
    unit: "Degree College Bhakhar",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Bhakkar",
    tehsil: "KaloorKot",
    unit: "kalurkot City",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Bhakkar",
    tehsil: "Bhakkar",
    unit: "Mundi town Bhakkar",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Bhakkar",
    tehsil: "Bhakkar",
    unit: "Bayhal",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Mianwali",
    district: "Bhakkar",
    tehsil: "KaloorKot",
    unit: "Rodi u",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Samundari",
    unit: "New City Town",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Samundari",
    unit: "Faisalabad Road",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Samundari",
    unit: "Chak no 473 GB",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Samundari",
    unit: "Zia Market",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Samundari",
    unit: "Government College Samundari",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Samundari",
    unit: "Aspair College",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Dijkot",
    unit: "Karkhana Bazar",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Dijkot",
    unit: "Awan Chowk",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Dijkot",
    unit: "Gover Higher Secondery School",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "Chak no 118 GB",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "Chak no 116 GB",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "Chak no 104 GB",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "Chak no 195 GB",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "Chak Jhumra",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "Government College Jhumra",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Tandlianwala",
    unit: "City Tandlianwala",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Tandlianwala",
    unit: "Government College Tandlianwala",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Tandlianwala",
    unit: "Mamon Kanjan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "GCUF Hostels",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "GCUF Old campus",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "GCUF New campus",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Faisalabad",
    tehsil: "Faisalabad",
    unit: "GCUF Community college",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Chiniot",
    tehsil: "Chiniot",
    unit: "City Chiniot",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Chiniot",
    tehsil: "Chiniot",
    unit: "Government College Chiniot",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Faisalabad",
    district: "Chiniot",
    tehsil: "Bhawana",
    unit: "Moza Barkhurdar",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Jhang",
    tehsil: "Jhang",
    unit: "Universitu Of Jhang",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Jhang",
    tehsil: "Shorkot",
    unit: "Govt College Shorkot",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Jhang",
    tehsil: "Shorkot",
    unit: "Shorkot City",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Jhang",
    tehsil: "18 Hazari",
    unit: "Hazari 18",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Jhang",
    tehsil: "Jhang",
    unit: "Chela",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Toba",
    unit: "Jamia Zariya Toba Campus",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Toba",
    unit: "Government College Toba",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Peer Mehal",
    unit: "Gov College Peer Mehal",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Peer Mehal",
    unit: "Peer Mehal",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Peer Mehal",
    unit: "Kamalia City",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Toba",
    unit: "Islam Pora",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Toba",
    unit: "New Islam Pora",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Toba",
    unit: "Garden Town",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Toba",
    unit: "Pera Coloney",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Jhang",
    district: "Toba",
    tehsil: "Toba",
    unit: "G B 149",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Al Shafa institute",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Royal college of Sciences",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Govt post Graduate college",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Apix college zafarwal",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "University of norwal",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Abdul wahab College",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Royal College",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Sahara college",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Standard College",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Norwal city",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Qillah Ahmed Abad",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Narowal",
    unit: "Bado Mahli",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Zafarwal",
    unit: "Zafarwal city",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Zafarwal",
    unit: "Jabal",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Zafarwal",
    unit: "Pandoori",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Zafarwal",
    unit: "Sabdodana",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Shakar Garh",
    unit: "Shakkar Garh",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Shakar Garh",
    unit: "Akhlas por",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Narowal",
    tehsil: "Shakar Garh",
    unit: "Noor kot",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Sialkot",
    tehsil: "Pasroor",
    unit: "Pasroor City",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Sialkot",
    tehsil: "Pasroor",
    unit: "Mohallah Dobangian",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Sialkot",
    tehsil: "Pasroor",
    unit: "Satrah pasroor",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Sialkot",
    tehsil: "Pasroor",
    unit: "Dolam Kahloo",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Sialkot",
    tehsil: "Daska",
    unit: "Daska city",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Sialkot",
    tehsil: "Daska",
    unit: "Sohawa",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Sialkot",
    district: "Sialkot",
    tehsil: "Daska",
    unit: "Motrah",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Nowshera Virka",
    unit: "Nowshera Virkan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Nowshera Virka",
    unit: "Garmula Virkan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Nowshera Virka",
    unit: "Doni Chak",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Nowshera Virka",
    unit: "Abid Abad",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Nowshera Virka",
    unit: "Degree College Nowshera Virkan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Nowshera Virka",
    unit: "Apex College Nowshera",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Nowshera Virka",
    unit: "Aspire College NOwshera Virkan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Wahndo",
    unit: "Wahndo",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Wahndo",
    unit: "Dandiyan",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Wahndo",
    unit: "Kali Soba",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Wahndo",
    unit: "Dalianwala",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Wahndo",
    unit: "Degree College Wahndo",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Wahndo",
    unit: "Scout College Wahndo",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Qila Dedar Singh",
    unit: "Kela DidarSingh",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Qila Dedar Singh",
    unit: "Sodra",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Qila Dedar Singh",
    unit: "More AimnaAbad",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Gujranwala",
    tehsil: "Qila Dedar Singh",
    unit: "Tatly Ali",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Wazirabad",
    tehsil: "Wazirabad",
    unit: "Apex College Wazirabad",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Wazirabad",
    tehsil: "Wazirabad",
    unit: "Ahmed nagar",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Wazirabad",
    tehsil: "Wazirabad",
    unit: "Klasky",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Wazirabad",
    tehsil: "Wazirabad",
    unit: "Ali pur",
    unitType: "Residential",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Wazirabad",
    tehsil: "Wazirabad",
    unit: "Wazirabad",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Wazirabad",
    tehsil: "Wazirabad",
    unit: "Kagamiter",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Wazirabad",
    tehsil: "Wazirabad",
    unit: "Dhonkal",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Hafizabad",
    tehsil: "Hafizabad",
    unit: "Degree College HAfizabad",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Hafizabad",
    tehsil: "Hafizabad",
    unit: "Hafizabad",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Hafizabad",
    tehsil: "Hafizabad",
    unit: "Panjgrain",
    unitType: "Educational",
  },
  {
    province: "Punjab North",
    division: "Gujranwala",
    district: "Hafizabad",
    tehsil: "Hafizabad",
    unit: "Kolo Tarar",
    unitType: "Educational",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Dadu",
    tehsil: "Dadu",
    unit: "Dadu",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Dadu",
    tehsil: "Mehar",
    unit: "Mehar",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Jacobabad",
    tehsil: "Jacobabad",
    unit: "Jacobabad",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Jacobabad",
    tehsil: "Mirpur Buriro",
    unit: "Mirpur Buriro",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Jacobabad",
    tehsil: "Mubarak Pur",
    unit: "Mubarak Pur",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Jacobabad",
    tehsil: "Thul",
    unit: "Thul",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kambar",
    tehsil: "Arzi Bhutto",
    unit: "Arzi Bhutto",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kambar",
    tehsil: "Qambar",
    unit: "Qambar",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kambar",
    tehsil: "Shahdadkot",
    unit: "Shahdadkot",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kambar",
    tehsil: "Sijawal",
    unit: "Sijawal",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kashmor",
    tehsil: "Kandhkot",
    unit: "Kandhkot",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kashmor",
    tehsil: "Ameenabad",
    unit: "Ameenabad",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kashmor",
    tehsil: "Ghouspur",
    unit: "Ghouspur",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kashmor",
    tehsil: "Guddu",
    unit: "Guddu",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kashmor",
    tehsil: "Karampur",
    unit: "Karampur",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kashmor",
    tehsil: "Kashmore",
    unit: "Kashmore",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Kashmor",
    tehsil: "Risaldar",
    unit: "Risaldar",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Larkana",
    tehsil: "Banguldero",
    unit: "Banguldero",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Larkana",
    tehsil: "Dhamra",
    unit: "Dhamra",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Larkana",
    tehsil: "Ratodero",
    unit: "Ratodero",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Larkana",
    tehsil: "Rohal Bugti",
    unit: "Rohal Bugti",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Shikarpur",
    tehsil: "Arain",
    unit: "Arain",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Shikarpur",
    tehsil: "Dari Jakhri",
    unit: "Dari Jakhri",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Shikarpur",
    tehsil: "Garho Maqam",
    unit: "Garho Maqam",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Shikarpur",
    tehsil: "Jindodero",
    unit: "Jindodero",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Shikarpur",
    tehsil: "Mian Shb",
    unit: "Mian Shb",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Larkana",
    district: "Shikarpur",
    tehsil: "Yousuf Bhatti",
    unit: "Yousuf Bhatti",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Badin",
    tehsil: "Badin City",
    unit: "Badin City",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Badin",
    tehsil: "Golarchi",
    unit: "Golarchi",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Badin",
    tehsil: "Koski",
    unit: "Koski",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Badin",
    tehsil: "Tando Bhago",
    unit: "Tando Bhago",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Badin",
    tehsil: "Talhar",
    unit: "Talhar",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Jamshoro",
    tehsil: "Jamshoro City",
    unit: "Jamshoro City",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Jamshoro",
    tehsil: "Kotri",
    unit: "Kotri",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Jamshoro",
    tehsil: "Thana Bhola Khna",
    unit: "Thana Bhola Khna",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Tando Allahyaar",
    tehsil: "Tando Allahyaar City",
    unit: "Tando Allahyaar City",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Tando Allahyaar",
    tehsil: "Chamar",
    unit: "Chamar",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Tando Mohammad Khan",
    tehsil: "Tando Muhammad Khan City",
    unit: "Tando Muhammad Khan City",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Tando Mohammad Khan",
    tehsil: "Raju Nizamani",
    unit: "Raju Nizamani",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Tando Mohammad Khan",
    tehsil: "Sehri",
    unit: "Sehri",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Tando Mohammad Khan",
    tehsil: "Matli",
    unit: "Matli",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Thata",
    tehsil: "Thatta City",
    unit: "Thatta City",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Thata",
    tehsil: "Jhark",
    unit: "Jhark",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Hyderabad",
    district: "Thata",
    tehsil: "Khameso Khan",
    unit: "Khameso Khan",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Mispur Khas",
    tehsil: "Tando Jan Muhammad",
    unit: "Tando Jan Muhammad",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Mispur Khas",
    tehsil: "Digri",
    unit: "Digri",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Mispur Khas",
    tehsil: "Juddho",
    unit: "Juddho",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Mispur Khas",
    tehsil: "Meerwah",
    unit: "Meerwah",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Mispur Khas",
    tehsil: "Tando Jan Muhammad College",
    unit: "Tando Jan Muhammad College",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Mispur Khas",
    tehsil: "Jamsabaad",
    unit: "Jamsabaad",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Thar Parkar",
    tehsil: "Mithi",
    unit: "Mithi",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Thar Parkar",
    tehsil: "Nokaot",
    unit: "Nokaot",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Umerkot",
    tehsil: "Kunri",
    unit: "Kunri",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Umerkot",
    tehsil: "Samaro",
    unit: "Samaro",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Umerkot",
    tehsil: "Road Samaro",
    unit: "Road Samaro",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Mirpur Khas",
    district: "Umerkot",
    tehsil: "Umerkot College",
    unit: "Umerkot College",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Nawbsha",
    tehsil: "Sakrand",
    unit: "Sakrand",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Nawbsha",
    tehsil: "Daur",
    unit: "Bandhi",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Noshero Feroz",
    tehsil: "Mehrab Pur",
    unit: "Mehrab Pur",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Noshero Feroz",
    tehsil: "Kandiaro",
    unit: "Boharti",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Noshero Feroz",
    tehsil: "Noshero Feroz",
    unit: "Noshero Feroz",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Noshero Feroz",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Sanghar",
    tehsil: "Tando Adam",
    unit: "Tando Adam",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Sanghar",
    tehsil: "Shadad Pur",
    unit: "Maldassi",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Sanghar",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Sanghar",
    tehsil: "Sanghar",
    unit: "7 Chak",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Sanghar",
    tehsil: "Sanjhoro",
    unit: "Khadro",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Sanghar",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Nawabsha",
    district: "Sanghar",
    tehsil: "Chak",
    unit: "Chak",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Ghotki",
    tehsil: "Ghotki",
    unit: "Ghotki",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Ghotki",
    tehsil: "Deharki",
    unit: "Deharki",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Ghotki",
    tehsil: "Obaro",
    unit: "Obaro",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Ghotki",
    tehsil: "Mirpur Mathelo",
    unit: "Mirpur Mathelo",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Khair Pur",
    tehsil: "Khair Pur City",
    unit: "Khair Pur City",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Khair Pur",
    tehsil: "Khan Pur",
    unit: "Khan Pur",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Khair Pur",
    tehsil: "Sethjara",
    unit: "Sethjara",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Khair Pur",
    tehsil: "Peer Jo Goth",
    unit: "Peer Jo Goth",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Sukkar",
    tehsil: "Pano Aqil",
    unit: "Pano Aqil",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Sukkar",
    tehsil: "Bagirji",
    unit: "Bagirji",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Sukkar",
    tehsil: "Ghumro",
    unit: "Ghumro",
    unitType: "Residential",
  },
  {
    province: "Sindh",
    division: "Sukkar",
    district: "Sukkar",
    tehsil: "Kalhori",
    unit: "Kalhori",
    unitType: "Residential",
  },
  {
    province: "AJK",
    division: "Nellum Valley",
    unit: "Degree College Authmoqam",
    unitType: "Educational",
  },
  {
    province: "AJK",
    division: "Nellum Valley",
    unit: "Katah Perran",
    unitType: "Residential",
  },
  {
    province: "AJK",
    division: "Nellum Valley",
    unit: "Mirpura",
    unitType: "Residential",
  },
  {
    province: "AJK",
    division: "Nellum Valley",
    unit: "Private College",
    unitType: "Educational",
  },
  {
    province: "AJK",
    division: "Nellum Valley",
    unit: "Salkhala",
    unitType: "Residential",
  },
  {
    province: "AJK",
    division: "Nellum Valley",
    unit: "Upper Valley",
    unitType: "Residential",
  },
  {
    province: "AJK",
    division: "Haveli",
    unit: "Private Colleges",
    unitType: "Educational",
  },
  {
    province: "AJK",
    division: "Haveli",
    unit: "CityHaveli",
    unitType: "Residential",
  },
  {
    province: "AJK",
    division: "Haveli",
    unit: "City Zone",
    unitType: "Residential",
  },
  {
    province: "AJK",
    division: "Haveli",
    unit: "Private Colleges",
    unitType: "Educational",
  },
  {
    province: "AJK",
    division: "Haveli",
    unit: "Degree College",
    unitType: "Educational",
  },
  {
    province: "AJK",
    division: "Haveli",
    unit: "University",
    unitType: "Educational",
  },
  {
    province: "AJK",
    division: "Haveli",
    unit: "High School",
    unitType: "Educational",
  },
  {
    province: "AJK",
    division: "Mirpur",
    unit: "Allama Iqbal College",
    unitType: "Educational",
  },
  {
    province: "AJK",
    division: "Mirpur",
    unit: "Degree College",
    unitType: "Educational",
  },
  {
    province: "AJK",
    division: "Mirpur",
    unit: "Dadyal City",
    unitType: "Residential",
  },
  {
    province: "AJK",
    division: "Mirpur",
    unit: "Tarutta",
    unitType: "Residential",
  },
  {
    province: "AJK",
    division: "Mirpur",
    unit: "Muslim Town",
    unitType: "Residential",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Dir Twon",
    unit: "Gdc Dir",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Dir",
    unit: "Qolanday",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Dir",
    unit: "Dir Khas",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Dir",
    unit: "Ganoray",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Dir",
    unit: "Gdc Hostal",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Barawl",
    unit: "Barawal Khas",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Larjam",
    unit: "Seray",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Larjam",
    unit: "Gandgar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Larjam",
    unit: "Bibyawar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Salarzoo",
    unit: "Sahib Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Salarzoo",
    unit: "Gang",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Khar",
    unit: "Haji Lawang",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Khar",
    unit: "Yusaf Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Wara Mamond",
    unit: "Chena Gay",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Khar",
    unit: "Maninzo",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Khar",
    unit: "Raghagan",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Khar",
    unit: "Gpgc Khar",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Wara Manond",
    unit: "Gdc Barhalozo",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Khar",
    unit: "Commerce College Khar",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Khar",
    unit: "Government Technical College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Bajaur",
    tehsil: "Otmanhel",
    unit: "Al Madina College Bajuar",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Lalqala",
    unit: "Manial",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Lalqala",
    unit: "Lalqela",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Lalqala",
    unit: "Zimdara",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Lalqala",
    unit: "Marhany",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Lalqala",
    unit: "Beshgram",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Lalqala",
    unit: "Gdc Lalqala",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Balambat",
    unit: "Hayaseri",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Balambat",
    unit: "Sangulay",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Balambat",
    unit: "Sherhaneee",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Samarbag",
    unit: "Gdc Samarbag",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Samarbag",
    unit: "Samarbag",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Samarbag",
    unit: "Kambat",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Samarbag",
    unit: "Maskene",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Samarbag",
    unit: "Sadbar Kala",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Samarbag",
    unit: "Meyaar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Samarbag",
    unit: "Shontala",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Munda",
    unit: "Munda Khas",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Munda",
    unit: "Rahem Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Lower",
    tehsil: "Munda",
    unit: "Hazana",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Wari",
    unit: "Sbbu Wari Campus",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Wari",
    unit: "Gdc Wari",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Wari",
    unit: "Government Technical Colleg ",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Wari",
    unit: "Commerce College Warii",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Wari",
    unit: "Tameer Watan College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Wari",
    unit: "The Crescent College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Wari",
    unit: "Allama Iqbal College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Dir",
    district: "Dir Upper",
    tehsil: "Wari",
    unit: "Ghss Wari",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Karak",
    tehsil: "That-E-Nasrati",
    unit: "Ambiri Kala",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Karak",
    tehsil: "That-E-Nasrati",
    unit: "That-E-Nasrati",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Karak",
    tehsil: "Karak",
    unit: "Sangatri Meeta Khel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Karak",
    tehsil: "Karak",
    unit: "Darab Kala",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Karak",
    tehsil: "Karak",
    unit: "Kkkuk (Khushal Khan Khattak University Karak)",
    unitType: "Educationnal",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Karak",
    tehsil: "Karak",
    unit: "Gpgc Karak",
    unitType: "Educationnal",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Karak",
    tehsil: "Banda Dawood Shah",
    unit: "Dagar Nari",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Karak",
    tehsil: "Karak",
    unit: "Sabir Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Kurram",
    tehsil: "Sadda",
    unit: "Pir Qayuom",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Kohat",
    district: "Hangu",
    tehsil: "Thall",
    unit: "Thall",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Ghazi",
    unit: "Ghazi City",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Ghazi",
    unit: "Qazi Pur",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Ghazi",
    unit: "Tarbela Colony",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Ghazi",
    unit: "Budha Ghazi",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Kangra Colony",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Ttp Colony",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Khalabutt",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Sikandarpur",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Talokar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Bandi Pirdad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Makhna Colony",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Abbottabad",
    tehsil: "Havelian",
    unit: "Havelian City",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Abbottabad",
    tehsil: "Havelian",
    unit: "Sultanpur",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Syed Maududi Unit",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Imam Hussain Unit",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Abu Bakar Siddique Unit",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Umer Farooque Unit",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Iqbal Hostel",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Jinnah Hostel",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Abbottabad",
    tehsil: "Havelian",
    unit: "Pharmacy Department",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Abbottabad",
    tehsil: "Havelian",
    unit: "Mlt Department",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Abbottabad",
    tehsil: "Havelian",
    unit: "It Department",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Abbottabad",
    tehsil: "Havelian",
    unit: "Chemistry Department",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Abbottabad",
    tehsil: "Havelian",
    unit: "Rehman Hostel",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Abbottabad",
    tehsil: "Havelian",
    unit: "Jadoon Hostel",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Haripur",
    unit: "Govt Degree College For Boys Haripur",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Haripur",
    district: "Haripur",
    tehsil: "Ghazi",
    unit: "Tameer -E- Seerat College Ghazi",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "Commerce College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "Gpgc Mansehra",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "Gpi Mansehra",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "Hhirs",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "Labarkot",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "Dara",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "City 1",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "City 2",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "Chitta Batta",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "Aghosh",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Mansehra",
    unit: "Nogazi",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Hazara University",
    unit: "Islamic Block",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Hazara University",
    unit: "Management Block",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Hazara University",
    unit: "Old Block",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Hazara University",
    unit: "Main Hostel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Hazara University",
    unit: "Gul Zaman Hostel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Hazara University",
    unit: "Faran Hostel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Hazara University",
    unit: "Abubakar Hostel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Hazara University",
    unit: "Momin Plaza",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Baffa Pakhal",
    unit: "Baffa",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Baffa Pakhal",
    unit: "Dhodial",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Balakot",
    unit: "Gdc Balakot",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Balakot",
    unit: "Commerce College Balakot",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Balakot",
    unit: "Bissian",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Balakot",
    unit: "Balakot City",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Balakot",
    unit: "Shohal",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Balakot",
    unit: "Kher Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Oghi",
    unit: "Oghi City",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Oghi",
    unit: "Sher Garh",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Mansehra",
    tehsil: "Oghi",
    unit: "Gdc Oghi",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Battagram",
    unit: "Sir Syed College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Battagram",
    unit: "Gdc Battagram",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Battagram",
    unit: "Battagaram City",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Battagram",
    unit: "Ajmera",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Battagram",
    unit: "Ghajbori",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Battagram",
    unit: "Kooza Banda",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Battagram",
    unit: "Chappar Gram",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Battagram",
    unit: "Shimlai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Battagram",
    unit: "Hazara University Sub Campus",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mansehra",
    district: "Battagram",
    tehsil: "Alai",
    unit: "Thakot",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Hira College Kanju",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Tipu Shaheed College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Hira College Kabal",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Hira School Sharifabad",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Govt.Degree College Kabal",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Kanju",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Gull Jaba",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Shah Dherai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Dardyal",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Muslim Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Sharif Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Sirsinai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Kotlai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Kabal",
    unit: "Kabal ",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Barikot",
    unit: "Shamozi",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Matta",
    unit: "Govt. Degree College Matta",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Matta",
    unit: "Pameer School Matta",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Matta",
    unit: "Hira Science College Matta",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Matta",
    unit: "Shakardara",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Matta",
    unit: "Matta Bazar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Bahrain",
    unit: "Gdc Madyan",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Bahrain",
    unit: "Madyan Bazar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Bahrain",
    unit: "Miandam",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Matta",
    unit: "Nazar Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Matta",
    unit: "Laabat",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Charbagh",
    unit: "Uni Of Swat",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Charbagh",
    unit: "Dhakorak",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Babuzai",
    unit: "Manglawar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Charbagh",
    unit: "Charbagh",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Charbagh",
    unit: "Alaa Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Bahrain",
    unit: "Ghss Kalam",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Bahrain",
    unit: "Kalam Bazar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Bahrain",
    unit: "Ashoran",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Bahrain",
    unit: "Shahoo",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Bahrain",
    unit: "Matiltan",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Swat",
    tehsil: "Bahrain",
    unit: "Banr Kalay",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Besham",
    unit: "Besham",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Puran",
    unit: "Shangla University",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Puran",
    unit: "Govt. Degree College Poran",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Puran",
    unit: "Saneela",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Puran",
    unit: "Hira College Puran",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Puran",
    unit: "Puran",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Puran",
    unit: "Iqra School Sandwai",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Puran",
    unit: "Chugah",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Puran",
    unit: "Bengalai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Swat",
    district: "Shangla",
    tehsil: "Puran",
    unit: "Ganorai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Behram Dheri",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Qutab Garh",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Sharif Kaly",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Momin Kaly",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Faqeer Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Dharha",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Spalano Dheri",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Khado Pull",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Korkaman Banda",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Jaban",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Floor Mill",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Dargai Kaly",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Makhnawala",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Wazir Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Qaldara",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Sharif Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Garhi Usmani Khel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Kharki",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Shengrai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Kachy Kaly",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Koper",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Qadar Kaly",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Ghani Dheri",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Malakand",
    tehsil: "Dargai",
    unit: "Sakhakot Khas",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Pati Kalan",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Dakko Baba",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Takkar (Sadda Bahar)",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Maday Baba",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Pir Saddi",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Chiragh Den Kaly",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Sardar Kaly",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Shah Nor Pull",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Deyar Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Parkho",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Umar Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Jalala",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Sarwar Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Mazdoor Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Topi",
    unit: "Kotha",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Topi",
    unit: "Meenai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Zaida",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Lahore",
    unit: "Jalbai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Bakar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Palo Dhandh",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Razarh",
    unit: "Yar Hussain Dagai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Razarh",
    unit: "Hospital Korona",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Razarh",
    unit: "Ghazi Kot",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Khadokhel",
    unit: "Totalai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Khadokhel",
    unit: "Totalai Dagai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Bam Khel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Murghuz",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Manerai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Garh Yousfi",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Internal Hostel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Dargai",
    tehsil: "Dargai",
    unit: "Dargai College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Lund Khwar College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Takht Bhai College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Takht Bhai",
    unit: "Technical College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Mardan",
    tehsil: "Katlang",
    unit: "Katlang College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Sawabi College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Razarh",
    unit: "Yar Hussain College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Zaida College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Lahore",
    unit: "Lahore College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Sawabi",
    unit: "Jamia Sawabi",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Khadokhel",
    unit: "Totalai College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Mardan",
    district: "Sawabi",
    tehsil: "Topi",
    unit: "Kotha College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Shah Alam",
    unit: "Twda",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Shah Alam",
    unit: "Wahid  Ghari",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Shah Alam",
    unit: "Khazana",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Shah Alam",
    unit: "Muslim Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Shah Alam",
    unit: "Nasapa",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Shah Alam",
    unit: "Ghss Nahaqqi",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Shah Alam",
    unit: "Muslim Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Shah Alam",
    unit: "Tauheed Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Shah Alam",
    unit: "Rehmat Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Mathra",
    unit: "Haryana",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Mathra",
    unit: "Mathra",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Mathra",
    unit: "Mechanai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Mathra",
    unit: "G.C Mathra",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Mathra",
    unit: "Mulazai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Mathra",
    unit: "Zorghary",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Mathra",
    unit: "Gul Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Chamkani",
    unit: "Nasirpur",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Peshawar",
    tehsil: "Chamkani",
    unit: "Bhudni",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Hakim Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Khat Kali",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Kaka Saib",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Rashakai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Barakhel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Kheshgi",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Nowshera Kalan",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Gpgc Nowshera",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Uet",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Nowshehra",
    unit: "Gcms 2 Nowshera",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Pabbi",
    unit: "Pashtoon Ghari",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Pabbi",
    unit: "Wazir Ghari",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Pabbi",
    unit: "Dag Ismail Khel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Pabbi",
    unit: "Uet Jalozai Campus",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Jehangira",
    unit: "Khairabad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Jehangira",
    unit: "Inzari",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Jehangira",
    unit: "Gdc Akora Khatak",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Nowshehra",
    tehsil: "Jehangira",
    unit: "Iqra College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Bara",
    unit: "Speen Qabar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Bara",
    unit: "Jahncy",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Bara",
    unit: "Mandikas",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Jamrood",
    unit: "Sor Kamar",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Jamrood",
    unit: "Ghondi",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Jamrood",
    unit: "Gdc Jamrood",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Landikotal",
    unit: "Shaikh Mal Khel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Landikotal",
    unit: "Sado Khel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Landikotal",
    unit: "Sultan Khel",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Khyber",
    tehsil: "Landikotal",
    unit: "Gdc Landikotal",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Charsadda",
    tehsil: "Shabqadar",
    unit: "Sarhad Kali",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Charsadda",
    tehsil: "Shabqadar",
    unit: "Katozai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Charsadda",
    tehsil: "Shabqadar",
    unit: "Cheshti Abad",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Charsadda",
    tehsil: "Shabqadar",
    unit: "Islamia School",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Charsadda",
    tehsil: "Shabqadar",
    unit: "Alkhidmat School",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Charsadda",
    tehsil: "Shabqadar",
    unit: "Degree College",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Charsadda",
    tehsil: "Shabqadar",
    unit: "Gonda",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Charsadda",
    tehsil: "Shabqadar",
    unit: "Nahaqqe",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Charsadda",
    tehsil: "Shabqadar",
    unit: "Panizai",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Mohmand",
    tehsil: "Safi",
    unit: "Ghazi Baig",
    unitType: "Residential",
    province: "KPK",
  },
  {
    division: "Peshawar",
    district: "Mohmand",
    tehsil: "Safi",
    unit: "Alkhidmat School",
    unitType: "Educational",
    province: "KPK",
  },
  {
    division: "Rakhshan",
    unit: "Noshki",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Rakhshan",
    unit: "Kharan",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Rakhshan",
    unit: "Degree College",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Quetta",
    unit: "Khanozai",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Quetta",
    unit: "Muslim Bagh",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Quetta",
    unit: "Chaman",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Banghar Colony",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Al Huda School",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Degree College",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "A 1 City",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Murad Colony",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Ali Ghar School",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Bhati Muhala",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Bhati Muhala",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Al Huda School",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Bhuto Muhala",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Chakra Muhala",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Jafar Abad City",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Sibi City",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Naser Abad",
    unit: "Shobat Pur City",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Qawadar City",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Sar Bandar",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Pasho Kan",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Pasni",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Degree College",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Technical College",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Dar-Ul-Aloom Public School",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Turbat City",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Baleda",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Atta Sha Degree Clg",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Panjgoor Coty",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Makhran",
    unit: "Degree College",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Lasbala",
    unit: "Bela",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Lasbala",
    unit: "Winder",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Lasbala",
    unit: "Awothal",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Lasbala",
    unit: "Hub",
    unitType: "Resedential",
    province: "Balochistan",
  },
  {
    division: "Lasbala",
    unit: "Degree College",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Lasbala",
    unit: "University Of Awothal",
    unitType: "Educational",
    province: "Balochistan",
  },
  {
    division: "Khuzdar",
    unit: "Khuzdar City",
    unitType: "Resedential",
    province: "Balochistan",
  },
];
module.exports = { divisionData };
